# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 40
  - vol_name: demo-vol-1-2
    vol_size: 20
  - vol_name: demo-vol-2-1
    vol_size: 40
  - vol_name: demo-vol-2-2
    vol_size: 20
  - vol_name: demo-vol-3-1
    vol_size: 40
  - vol_name: demo-vol-3-2
    vol_size: 20

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchDB_5984
    description: "Security group for couchDB 5984"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_cluster
    description: "Security group for couchdb cluster"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: couchdb_cluster
  - name: docker_swarm
    description: "Security group for docker swarm"
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_group: docker_swarm
  - name: erlang_cluster
    description: "Security group for erlang cluster"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: erlang_cluster
  - name: web_ui
    description: "Web UI port"
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-1
    volumes: ['demo-vol-1-1', 'demo-vol-1-2']
  - name: demo-2
    volumes: ['demo-vol-2-1', 'demo-vol-2-2']
  - name: demo-3
    volumes: ['demo-vol-3-1', 'demo-vol-3-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: wzx2
instance_flavor: uom.mse.2c9g