# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-vol-4-1
    vol_size: 40
  - vol_name: demo-vol-4-2
    vol_size: 20

# Security group
security_groups:
  - name: demo_ssh
  - name: demo_http
  - name: couchDB_5984
  - name: couchdb_cluster
  - name: docker_swarm
  - name: erlang_cluster
  - name: web_ui

# Instance
instances:
  - name: demo-4
    volumes: ['demo-vol-4-1', 'demo-vol-4-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: wzx2
instance_flavor: uom.mse.2c9g