---
- name: Add proxy in /etc/environment
  tags: 'instance proxy'
  become: yes
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
      http_proxy=http://wwwproxy.unimelb.edu.au:8000/
      https_proxy=http://wwwproxy.unimelb.edu.au:8000/ 
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au

- name: Reboot a machine
  tags: 'instance proxy'
  become: yes
  reboot:
    reboot_timeout: 3000

- name: Install vim
  tags: 'instance proxy'
  become: yes
  apt:
    name: ['vim']
    state: latest
    install_recommends: no
    update_cache: yes